# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

xcodeproj '/Users/jamesfazio/Git/AuctionAppiOS/AuctionApp/AuctionApp.xcodeproj'

pod 'SDWebImage', '~>3.6'
pod 'SalesforceMobileSDK-iOS'

target 'AuctionApp' do

end

target 'AuctionAppTests' do

end

